// <auto-generated />
namespace learnaspnet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class populateGenero : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populateGenero));
        
        string IMigrationMetadata.Id
        {
            get { return "201712281644034_populateGenero"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
